version = 1
name = "clw-cash-signer"
uuid = "enclave_dc9a8ad33667"
app_uuid = "app_366535fdf2b7"
team_uuid = "team_e48a089e94da"
debug = true
dockerfile = "./enclave/Dockerfile"
api_key_auth = true
trx_logging = true
tls_termination = true
forward_proxy_protocol = false
trusted_headers = []

[healthcheck]
path = "/health"
port = 7000

[egress]
enabled = false

[scaling]
desired_replicas = 1

[service]
port = 7000

[signing]
certPath = "./infra/cert.pem"
keyPath = "./infra/key.pem"

[attestation]
HashAlgorithm = "Sha384 { ... }"
PCR0 = "a0b3519352052e08dffd1745978a2617d0810e20cef9e514d8da294e45ebe15924ceda4721df613f5b9e2bb7cc32e3d6"
PCR1 = "0343b056cd8485ca7890ddd833476d78460aed2aa161548e4e26bedf321726696257d623e8805f3f605946b3d8b0c6aa"
PCR2 = "f3aee70f86853d097266a4ee620ab9202bd775b28989219205b9dc637a3eae2ec4382a0792a0f4aaa3c61dfd0d01f68c"
PCR8 = "ab2fb6f40392d68b8ebb4d6e97dfb46d04101de4a54312320f8d1de707203390b03cb0f0ee4b29fdd5a94f0fa34ec1d3"
