version = 1
name = "clw-cash-signer"
uuid = "enclave_dc9a8ad33667"
app_uuid = "app_366535fdf2b7"
team_uuid = "team_e48a089e94da"
debug = true
dockerfile = "./enclave/Dockerfile"
api_key_auth = true
trx_logging = true
tls_termination = true
forward_proxy_protocol = false
trusted_headers = []

[healthcheck]
path = "/health"
port = 7000

[egress]
enabled = false

[scaling]
desired_replicas = 1

[service]
port = 7000

[signing]
certPath = "./infra/cert.pem"
keyPath = "./infra/key.pem"

[attestation]
HashAlgorithm = "Sha384 { ... }"
PCR0 = "17ed9b0f822f5d5253fbc3726c2e2b7df56b1713999f83b21ca05348fd11f00e2ae542bb4a8477b4aeb36bdfd01cda1e"
PCR1 = "0343b056cd8485ca7890ddd833476d78460aed2aa161548e4e26bedf321726696257d623e8805f3f605946b3d8b0c6aa"
PCR2 = "15d6e0dbce3fc09c5b08064f4fd2c3469e9761f26b63fe182bc160cea1e10df9ae0482968560ed8652ddf132c148d51a"
PCR8 = "ab2fb6f40392d68b8ebb4d6e97dfb46d04101de4a54312320f8d1de707203390b03cb0f0ee4b29fdd5a94f0fa34ec1d3"
