version = 1
name = "clw-cash-signer"
uuid = "enclave_dc9a8ad33667"
app_uuid = "app_366535fdf2b7"
team_uuid = "team_e48a089e94da"
debug = true
dockerfile = "./enclave/Dockerfile"
api_key_auth = true
trx_logging = true
tls_termination = true
forward_proxy_protocol = false
trusted_headers = []

[healthcheck]
path = "/health"
port = 7000

[egress]
enabled = true
destinations = ["arkade.computer"]

[scaling]
desired_replicas = 1

[service]
port = 7000

[signing]
certPath = "./infra/cert.pem"
keyPath = "./infra/key.pem"

[attestation]
HashAlgorithm = "Sha384 { ... }"
PCR0 = "a54033d4c440e3be08bffa0b1afea27dd92002de7861b337e9b42e74b827a03de6cbebf466a72e6fbf0aff8f9e19b4ae"
PCR1 = "0343b056cd8485ca7890ddd833476d78460aed2aa161548e4e26bedf321726696257d623e8805f3f605946b3d8b0c6aa"
PCR2 = "850b655596f12de59f1ae5bb8b8c80d1f8ec061370e57a540852474ff864f95bcd86a2c3b9091cba2131701cd29269ec"
PCR8 = "ab2fb6f40392d68b8ebb4d6e97dfb46d04101de4a54312320f8d1de707203390b03cb0f0ee4b29fdd5a94f0fa34ec1d3"
